# SPDX-License-Identifier: GPL-2.0
ifeq ($(CONFIG_ARCH_ROCKCHIP), y)

dtbo-$(CONFIG_CPU_RK3576) += \
	rk3576-armsom-can0-m2-overlay.dtbo \
	rk3576-armsom-can1-m1-overlay.dtbo \
	rk3576-armsom-can1-m2-overlay.dtbo \
	rk3576-armsom-can1-m3-overlay.dtbo \
	rk3576-armsom-i2c0-m1-overlay.dtbo \
	rk3576-armsom-i2c3-m0-overlay.dtbo \
	rk3576-armsom-i2c3-m1-overlay.dtbo \
	rk3576-armsom-i2c4-m1-overlay.dtbo \
	rk3576-armsom-i2c4-m3-overlay.dtbo \
	rk3576-armsom-i2c6-m2-overlay.dtbo \
	rk3576-armsom-i2c6-m3-overlay.dtbo \
	rk3576-armsom-i2c7-m1-overlay.dtbo \
	rk3576-armsom-i2c7-m2-overlay.dtbo \
	rk3576-armsom-i2c8-m2-overlay.dtbo \
	rk3576-armsom-i2c9-m1-overlay.dtbo \
	rk3576-armsom-pwm0-ch0-m1-overlay.dtbo \
	rk3576-armsom-pwm0-ch0-m3-overlay.dtbo \
	rk3576-armsom-pwm0-ch1-m0-overlay.dtbo \
	rk3576-armsom-pwm1-ch0-m1-overlay.dtbo \
	rk3576-armsom-pwm1-ch0-m3-overlay.dtbo \
	rk3576-armsom-pwm1-ch1-m1-overlay.dtbo \
	rk3576-armsom-pwm2-ch2-m1-overlay.dtbo \
	rk3576-armsom-pwm2-ch3-m3-overlay.dtbo \
	rk3576-armsom-pwm2-ch5-m1-overlay.dtbo \
	rk3576-armsom-pwm2-ch6-m1-overlay.dtbo \
	rk3576-armsom-pwm2-ch6-m3-overlay.dtbo \
	rk3576-armsom-pwm2-ch7-m3-overlay.dtbo \
	rk3576-armsom-spi1-m0-overlay.dtbo \
	rk3576-armsom-spi3-m0-overlay.dtbo \
	rk3576-armsom-spi3-m1-overlay.dtbo \
	rk3576-armsom-uart2-m1-overlay.dtbo \
	rk3576-armsom-uart2-m2-overlay.dtbo \
	rk3576-armsom-uart3-m0-overlay.dtbo \
	rk3576-armsom-uart3-m1-overlay.dtbo \
	rk3576-armsom-uart4-m0-overlay.dtbo \
	rk3576-armsom-uart5-m0-overlay.dtbo \
	rk3576-armsom-uart6-m0-overlay.dtbo \
	rk3576-armsom-uart6-m3-overlay.dtbo \
	rk3576-armsom-uart7-m0-overlay.dtbo \
	rk3576-armsom-uart8-m2-overlay.dtbo \
	rk3576-armsom-uart10-m1-overlay.dtbo \
	rk3576-armsom-uart10-m2-overlay.dtbo \
	rk3576-armsom-rgmii-gmac1-overlay.dtbo \
	rk3576-armsom-cm5-io-camera-imx219-cs0-overlay.dtbo \
	rk3576-armsom-cm5-io-camera-ov13850-cs1-overlay.dtbo \
	rk3576-armsom-cm5-io-display-1200x1900-10.1hd-overlay.dtbo \
	rk3576-armsom-hdmi-disabled-overlay.dtbo \
	rk3576-armsom-dp-disabled-overlay.dtbo \
	rk3576-armsom-sige5-camera-ov13850-cs0-overlay.dtbo \
	rk3576-armsom-sige5-camera-ov13850-cs1-overlay.dtbo \
	rk3576-armsom-sige5-display-1200x1900-10.1hd-overlay.dtbo 

dtbo-$(CONFIG_CPU_RK3588) += \
	rk3588-armsom-aim7-display-800x1280-8hd-overlay.dtbo \
	rk3588-armsom-aim7-camera-overlay.dtbo \
	rk3588-armsom-can1-m0.dtbo \
	rk3588-armsom-can1-m1.dtbo \
	rk3588-armsom-i2c0-m1.dtbo \
	rk3588-armsom-i2c1-m0.dtbo \
	rk3588-armsom-i2c3-m1.dtbo \
	rk3588-armsom-i2c7-m3.dtbo \
	rk3588-armsom-i2c8-m4.dtbo \
	rk3588-armsom-pwm2-m1.dtbo \
	rk3588-armsom-pwm3-m1.dtbo \
	rk3588-armsom-pwm5-m2.dtbo \
	rk3588-armsom-pwm6-m2.dtbo \
	rk3588-armsom-pwm7-m3.dtbo \
	rk3588-armsom-pwm8-m0.dtbo \
	rk3588-armsom-pwm12-m0.dtbo \
	rk3588-armsom-pwm13-m0.dtbo \
	rk3588-armsom-pwm13-m2.dtbo \
	rk3588-armsom-pwm14-m0.dtbo \
	rk3588-armsom-pwm14-m1.dtbo \
	rk3588-armsom-pwm15-m0.dtbo \
	rk3588-armsom-pwm15-m1.dtbo \
	rk3588-armsom-pwm15-m2.dtbo \
	rk3588-armsom-spi0-m2-cs0-cs1-spidev.dtbo \
	rk3588-armsom-spi1-m1-cs0-spidev.dtbo \
	rk3588-armsom-spi1-m1-cs1-spidev.dtbo \
	rk3588-armsom-sige7-camera-imx415-4k-overlay.dtbo \
	rk3588-armsom-sige7-camera-ov13850-csi0-overlay.dtbo \
	rk3588-armsom-sige7-camera-ov13850-csi1-overlay.dtbo \
	rk3588-armsom-sige7-display-1200x1900-10.1hd-overlay.dtbo \
	rk3588-armsom-uart2-m0.dtbo \
	rk3588-armsom-uart2-m2.dtbo \
	rk3588-armsom-uart3-m1.dtbo \
	rk3588-armsom-uart4-m2.dtbo \
	rk3588-armsom-uart7-m1.dtbo \
	rk3588-armsom-uart7-m2.dtbo \
	rk3588-armsom-w3-display-1200x1900-10.1hd-overlay.dtbo \
	rk3588-armsom-w3-camera-ov13850-csi0-overlay.dtbo
endif

dtbotxt-$(CONFIG_ARCH_ROCKCHIP) += \
	README.md

targets += $(dtbo-y) $(dtbotxt-y)

always-y		:= $(dtbo-y) $(dtbotxt-y)
clean-files		:= *.dtbo
